databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: yurij_v@ukr.net
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: quohen
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:kzs1Fi62IvH7oVH6xVOmKpT/I2ujXYJM:ZuzETEXRNOC3iLq5t683+9pqsFwfEGqoSkFJkIZt4F7144G+QWCIzwMoLt7MGeBfRC5L85XI1SDsPgVSdPQp09ve]
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Faji3Wu/TW8EdsHAUCPy2gZgNJF0vHWP:XvIwMbwMBmCau2Bm5C+qUramBlh333DP08jQxbNdOO5l+CA4OHZ1u9mCQ1NIPjoKe27ZzNueFi8OsjGztH/g1EK/]
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:s031eHsG4ZhZrWrla4+SM5JB998SNQ9F:L9aTdWCeOjqgG0RqVCJolMKxdSf/OUAjahqDg+rT6y6WCfd2]
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:jCjvJAZwkdRa2QV0tfnpBGNnaIYrZwdo:5PAQyGrk/o/dAhaY+siVNCr4EDiIwQOhengQZojFwgAyMqbqZDElINezIVfIJzZ3jUcXCd4/XZlNEdg=]
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: trydjango32
- key: OCR_API_TOKEN_HEADER
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:SjjuB8C+3JScJkhDe6NFYOS19d04Iiw/:LGp9KjNKfBdfHoAZjiVqSmREXLK65XwR/RIFgZYwFi98ayV3ySuQj6je7vNyjPpFzc7RKl4raCmoTvw=]
- key: OCR_API_ENDPOINT
  scope: RUN_AND_BUILD_TIME
  value: https://fastapi-microservice-for-django-d3kjd.ondigitalocean.app
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  git:
    branch: production-4
    repo_clone_url: https://github.com/Quohen-Leth/Try-Django-3.2.git
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: python manage.py migrate --noinput
  source_dir: /
name: try-django-3-2
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  git:
    branch: production-4
    repo_clone_url: https://github.com/Quohen-Leth/Try-Django-3.2.git
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: try-django-3-2
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /
